routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()) {
        return redirect()->route('home');
    }
    return view('auth.login');
});

Auth::routes();

Route::get('test', function() {
    Storage::disk('google')->put('test.txt', 'Hello World');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');

	//Master
    Route::group(['namespace' => 'Masters', 'prefix' => 'master'], function() {
       // Route::get('master/location-centre-master', 'LocationCentreMaster');
        
        Route::resource('location-centre-master', 'LocationCentreMasterController');
        
        Route::resource('department-centre-master', 'DepartmentCentreMasterController');
      	
      	Route::get('get-employee-details/{id}', 'EmployeeMasterController@get_employee_details')->name('getEmployeeDetails');
        Route::resource('employee-master', 'EmployeeMasterController');

        Route::resource('project-master', 'ProjectMasterController');

        Route::resource('beneficiary-master', 'BeneficiaryMasterController');

        Route::resource('holiday-master', 'HolidayMasterController');

        Route::resource('office-hours-master', 'OfficeHoursMasterController');

        Route::resource('roles','RoleMasterController');


    });

    //Attendance
    Route::group(['namespace' => 'Attendance', 'prefix' => 'attendance'], function() {
        
        Route::get('location-details', 'MarkAttendanceController@ip_details')->name('getLocation');
        Route::get('show-attendance', 'MarkAttendanceController@show_attendance_index')->name('showAttendance');
        Route::post('show-attendance', 'MarkAttendanceController@find_attendance')->name('findAttendance');
        Route::resource('mark-attendance', 'MarkAttendanceController');

    });

    //Outdoor Duty
    Route::group(['namespace' => 'OutdoorDuty'], function() {
        
        Route::put('outdoor-duty/email-list/delete/{id?}', 'EmailListController@delete')->name('delete_email');
        Route::resource('outdoor-duty/email-list', 'EmailListController', ['names' => 'email-list']);

        Route::put('outdoor-duty/approval-process/{id}', 'OutdoorDutyController@approval_process');
        Route::resource('outdoor-duty', 'OutdoorDutyController');

    });

    //leave-application
    Route::group(['namespace' => 'LeaveApplication'], function() {
        
        Route::put('leave-application/approval-process/{id}', 'LeaveApplicationController@approval_process');
        Route::resource('leave-application', 'LeaveApplicationController');

    });

    //Report
    Route::group(['namespace' => 'Report', 'prefix' => 'reports'], function() {
        
        Route::get('export-attendance', 'AttendanceReportController@export_attendance')->name('export-attendance');
        Route::get('export-attendance-horizontal', 'AttendanceReportController@export_attendance_horizontal')->name('export-attendance-horizontal');
        Route::get('attendance-report', 'AttendanceReportController@index')->name('attendance-report.index');

    });

        //Content Manager
        Route::group(['namespace' => 'ContentManager', 'prefix' => 'content-manager'], function() {
           // Route::get('master/location-centre-master', 'LocationCentreMaster');
            
            Route::get('get-access-token', 'UploadContentController@get_access_token');
            Route::resource('upload-content', 'UploadContentController');
            
            Route::resource('pending-approval-content', 'PendingApprovalContentController');

            Route::get('approved-content', 'ApprovedContentController@index')->name('approved-content.index');
        });
});

Route::get('get-google-drive-file', function() {
    $filename = 'banner_-_3_82.png';

    $dir = '/';
    $recursive = false; // Get subdirectories also?
    $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

    $file = $contents
        ->where('type', '=', 'file')
        ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME))
        ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION))
        ->first(); // there can be duplicate file names!

    dd($file['path']);

    $rawData = Storage::disk('google')->get($file['path']);

    return response($rawData, 200)
        ->header('ContentType', $file['mimetype'])
        ->header('Content-Disposition', "attachment; filename='$filename'");
});


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

});

Route::get('clock-in-reminder', 'Commands\AttendanceReminderController@clock_in_reminder');
Route::get('clock-out-reminder', 'Commands\AttendanceReminderController@clock_out_reminder');
Route::get('update-attendance-status', 'Commands\UpdateAttendanceStatusController@index');

app/Http/Controllers/ContentManager/ApprovedContentController.php
<?php

namespace App\Http\Controllers\ContentManager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Masters\ProjectMaster;
use App\Model\ContentManager\ContentManager;
use App\Model\ContentManager\ContentFiles;

class ApprovedContentController extends Controller
{
    public function index(Request $request){
    	$content_files = [];
        // return $request->all();
         if (count((array)$request->all()) == 0) {
            \Session::forget('data');
            $content_files = ContentFiles::orderBy('id', 'asc')->where('approval_status',1);
        }
        else {
            if(isset($request->search) && count($request->search) > 0)
            {
                \Session::forget('data');
            }
            \Session::push('data', $request->search);
             $content_files = ContentFiles::orderBy('id', 'asc')->where('approval_status',1);
            if (count((array)\Session::get('data')[0]) > 0) {
                                
                $query = ContentFiles::orderBy('id', 'asc')->where('approval_status',1);
                
                foreach (\Session::get('data')[0] as $content_file)
                {
                    
                    if( $content_file['column'] == 'project_name' ){
                    	$query->whereHas('project', function($query1) use ($content_file){
                        	$query1->where('name', 'LIKE', '%'. $content_file['search_data'] .'%');
                    	});
                    }

                    if( $content_file['column'] == 'donor' ){
                    	$query->whereHas('project', function($query1) use ($content_file){
                        	$query1->where('donor', 'LIKE', '%'. $content_file['search_data'] .'%');
                    	});
                    }

                    if( $content_file['column'] == 'photo_period' ){
                    	$query->where('photo_period', 'LIKE', '%'. $content_file['search_data'] .'%');
                    }
                    if( $content_file['column'] == 'date' ){
                    	$query->where('date', date_ymd($content_file['search_data']) );
                    }
                    if( $content_file['column'] == 'uploaded_by' ){
                    	$query->whereHas('created_by', function($query1) use ($content_file){
                        	$query1->where('name', 'LIKE', '%'. $content_file['search_data'] .'%');
                    	});
                    }

                    if( $content_file['column'] == 'file_caption' ){
                    	$query->where('file_caption', 'LIKE', '%'. $content_file['search_data'] .'%');
                    }
                    if( $content_file['column'] == 'content_type' ){
                    	$query->where('content_type', 'LIKE', '%'. $content_file['search_data'] .'%');
                    }
                }
                $content_files = $query;
                
            }
        }

        $content_files = $content_files->paginate(10);
    	$columns = ['project_name', 'photo_period', 'donor', 'date', 'uploaded_by', 'file_caption', 'content_type'];
    	return view('content_manager.approved_content.index', compact('columns', 'content_files'));
    }
}

app/Http/Controllers/ContentManager/PendingApprovalContentController.php
<?php

namespace App\Http\Controllers\ContentManager;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Masters\ProjectMaster;
use App\Model\ContentManager\ContentFiles;
use Illuminate\Support\Facades\File; 
class PendingApprovalContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {   
        $projects = [];
        // return $request->all();
         if (count((array)$request->all()) == 0) {
            \Session::forget('data');
            $projects = ProjectMaster::orderBy('id', 'asc');
        }
        else {
            if(isset($request->search) && count($request->search) > 0)
            {
                \Session::forget('data');
            }
            \Session::push('data', $request->search);
             $projects = ProjectMaster::orderBy('id', 'asc');
            if (count((array)\Session::get('data')[0]) > 0) {
                                
                $query = ProjectMaster::orderBy('id', 'asc');
                
                foreach (\Session::get('data')[0] as $project)
                {
                    if( $project['column'] == 'project_name' ){
                        $query->where('name', 'LIKE', '%'. $project['search_data'] .'%');
                    }
                }
                $projects = $query;
                
            }
        }

        $projects = $projects->paginate(10);
        $columns = ['project_name'];
        return view('content_manager.pending_approval_content.index', compact('columns', 'projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $project = ProjectMaster::find($id);

        if( isset($request->content_type) ){

            \Session::forget('content_type');
            \Session::forget('content_period');

            \Session::push('content_type', $request->content_type);
            \Session::push('content_period', $request->content_period);
        }

        $page =1;
        if( isset($request->page) ){
            $page = $request->page;
        }

        $content_type = \Session::get('content_type')[0];
        $content_period = \Session::get('content_period')[0];
        $content_files = ContentFiles::where('project_id', $id)->where('content_type', $content_type)->where('content_period', $content_period)->whereNull('approval_status')->paginate(3, // per page (may be get it from request)
                                ['*'], // columns to select from table (default *, means all fields)
                                'page', // page name that holds the page number in the query string
                                $page // current page, default 1
                                );

        return view('content_manager.pending_approval_content.edit', compact('project', 'content_files'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $project = ProjectMaster::find($id);

        \DB::beginTransaction();
            foreach ($request->content_file as $id => $data) {

                $content_file = ContentFiles::find($id);
                $content_file->file_caption = $data['file_caption'];
                $content_file->date = date_ymd($data['date']);
                
                if( !is_null($data['approval_status']) ){
                    $content_file->approval_status = $data['approval_status'];
                    if( $data['approval_status'] == 0){
                        \Storage::disk('google')->delete($content_file->file_path);
                    }
                }

                if(array_key_exists('content', $data))
                {
                    $file = $data['content'];
                    $file_name = explode(".", $file->getClientOriginalName());
                    $filename = $file_name[0];
                    $ext = $file_name[ sizeof($file_name)-1 ];
                    $file_path = '\uploads\content_manager';
                    $file_name = str_replace(' ', '_', strtolower($filename))."_".$content_file->content_manager_id. '.' . $ext;
                    
                    // Delete previous File
                        \Storage::disk('google')->delete($content_file->file_path);

                    \Storage::disk('google')->put($file_name, file_get_contents($file));

                    // Get the uploaded file to store it's Google Drive File ID
                    $dir = '/';
                    $recursive = false; // Get subdirectories also?
                    $contents = collect(\Storage::disk('google')->listContents($dir, $recursive));

                    $gdrive_uploaded_file = $contents
                        ->where('type', '=', 'file')
                        ->where('filename', '=', pathinfo($file_name, PATHINFO_FILENAME))
                        ->where('extension', '=', pathinfo($file_name, PATHINFO_EXTENSION))
                        ->first(); // there can be duplicate file names!

                    $content_file->file_path = $gdrive_uploaded_file['path'];
                    $content_file->file_name = $file_name;
                }

                $content_file->update();    
        }
        \DB::commit();
        session()->flash('status',"Files Updated Successfully");
        return redirect()->route('pending-approval-content.index');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/content_manager/pending_approval_content/edit.blade.php
@extends('layouts.app', ['activePage' => 'pending-approval-content', 'titlePage' => __('Pending Approval Content')])

@section('title') Pending Approval Content @endsection


@section('page-level-css')
    <link href="{{ asset('material') }}/plugins/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datepicker-master/dist/datepicker.css')}}" rel="stylesheet" type="text/css" />
    <style type="text/css">
      input.content_type_radio {
          margin: 0 5px;
      }
      img.img_preview {
          object-fit: contain;
      }
      p.status_text {
          margin: 4% 0;
          text-align: center;
          color: #fff;
          font-weight: 600;
          border: 1px solid;
          padding: 4%;
          border-radius: 5px;
      }
      p.status_text.approve {
          color: #fff;
          background-color: #469e46;
      }
      p.status_text.disapprove {
          color: #fff;
          background-color: #d00000;
      }

    </style>
@endsection

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary" data-color="orange">
        <h4 class="card-title">Project : {{ $project->name }} </h4>
      </div>
      <div class="card-body">
        @if(count($errors) > 0)
            <div class="alert alert-danger">
                <h6> Errors </h6>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="POST" action="{{ route('pending-approval-content.update', $project->id) }}" enctype="multipart/form-data">
          @csrf
          @method('PUT')
          <input type="hidden" name="project_id" value="{{  $project->id }}">

          <div class="row content_row">
            @foreach( $content_files as $key => $files )
              <div class="col-md-4 single_file_column">
                      
                  <label style="display: block;"> File Preview: </label>

                  @php
                    $file = $files->file_path."/".$files->file_name;
                    $real_file = "https://drive.google.com/uc?id=".$files->file_path;

                    \Log::info($real_file);
                  @endphp

                  @if( $files->content_type == "document" )
                    <iframe class="file_preview" src="{{ URL($file)  }}" width="500" height="300"></iframe>
                  @elseif( $files->content_type == "photo" )
                    <img class="img_preview" src="{{ URL($real_file) }}" width="500" height="300">
                  @endif
                  <div class="row">
                    <div class="col-md-4">
                      <label>Replace content</label>

                      @php
                        $accept_content = "";
                        if( $files->content_type == "photo" )
                          $accept_content = ".jpeg, .jpg, .png";
                        elseif($files->content_type == "document" )
                          $accept_content = ".pdf, .docx";

                      @endphp

                      <input type="file" class="upload-file" name="content_file[{{$files->id}}][content]" accept="{{ $accept_content }}">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <textarea class="form-control caption" name="content_file[{{$files->id}}][file_caption]" placeholder="Enter Caption">{{ $files->file_caption }}</textarea>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <input type="text" class="form-control date" id="date" name="content_file[{{$files->id}}][date]" placeholder="Enter Date" value="{{ date_dmy($files->date) }}">
                    </div>
                  </div>
                  <div class="row approval_row">
                      <input type="hidden" class="approval_status" name="content_file[{{$files->id}}][approval_status]" value="">
                    <div class="col-md-4 approval-column">
                      <a href="javascript:void(0)" class="btn status_button approve_button" style="width: 100%;"><i class="fa fa-check" style="color: green;"></i></a>
                    </div>
                    <div class="col-md-4 disapproval-column">
                      <a href="javascript:void(0)" class="btn status_button disapprove_button" style="width: 100%;"><i class="fa fa-trash" style="color: red;"></i></a>
                    </div>
                  </div>
              </div>
            @endforeach
            <div class="col-md-12">
              {{ $content_files->render() }}
            </div>
          </div>

        </div>


          @can('review-content')
            <div class="row">
              <div class="col-md-3 offset-4">
                <input type="submit" name="" class="btn" value="Submit" style="width: 100%; background-color: #fa9f19; font-weight: 600; color: #fff;">
              </div>
            </div>
          @endcan
          
        </form>

      </div>
    </div>

  </div>
</div>
@endsection

@section('page-level-plugins-js')
    <script src="{{ URL::asset('template/assets/global/plugins/scripts/datatable.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-select/js/bootstrap-select.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datepicker-master/dist/datepicker.js')}}" type="text/javascript"></script>
    

@endsection

@section('page-level-scripts-js')

  <script type="text/javascript">
    

    $(document).ready(function(){


        $(".date").datepicker({
            format      :   "dd-mm-yyyy",
            viewMode    :   "years", 
        });
        
        fadeOuttime = 1000;
        $('.approve_button').click(function(){
          $( $(this).parents('.approval_row').find('.approval_status') ).val(1);


          $(this).fadeOut(fadeOuttime, () => { 
              $(this).parents('.approval-column').append('<p class="status_text approve">Approved</p>').fadeIn(2000);
          });
          $(this).parents('.approval_row').find('.disapprove_button').fadeOut(fadeOuttime);
          
        })
        $('.disapprove_button').click(function(){
          $( $(this).parents('.approval_row').find('.approval_status') ).val(0);

          $this = this;
          $(this).fadeOut(fadeOuttime, () => { 
              $($this).parents('.approval_row').find('.approval-column').append('<p class="status_text disapprove">Disapproved</p>').fadeIn(2000);
          });

          $(this).parents('.approval_row').find('.approve_button').fadeOut(fadeOuttime);

        })

        $('.status_button').click(function(){
          
          $this = this;
          $this = this;
          setTimeout(function () {
              $($this).parents('.approval_row').find('.disapproval-column').append('<a href="javascript:void(0)" class="btn cancel_button" style="width: 100%;">Cancel</a>');
            }, 1000);
        })

        $(document).on('click', '.cancel_button', function(){
          $(this).fadeOut(fadeOuttime);
          $('.status_text').fadeOut(fadeOuttime);

          $this = this;
          setTimeout(function () {
              $($this).parents('.approval_row').find('.approve_button').fadeIn(fadeOuttime);
              $($this).parents('.approval_row').find('.disapprove_button').fadeIn(fadeOuttime);
            }, fadeOuttime);

          $( $(this).parents('.approval_row').find('.approval_status') ).val("");

        })

        $(document).on('change','.upload-file', function(){
            readURL(this);
        })
        
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {

                    var file = input.files[0];
                    var fileType = file["type"];
                    var validImageTypes = ["application/"];
                    if( fileType == "application/pdf"){
                      $(input).parents('.single_file_column').find('.img_preview').hide();
                      $('.excel_preview').hide();
                      $(input).parents('.single_file_column').find('.file_preview').show();
                      $(input).parents('.single_file_column').find('.file_preview').attr('src', e.target.result);
                  }
                  else if( fileType == "image/jpeg" || fileType == "image/jpg" || fileType == "image/png"){
                      $(input).parents('.single_file_column').find('.file_preview').hide();
                      $(input).parents('.single_file_column').find('.img_preview').show();
                      $(input).parents('.single_file_column').find('.img_preview').attr('src', e.target.result);
                      $(input).parents('.single_file_column').find('.img_preview').show();
                        console.log( $(input).parents('.single_file_column').find('.img_preview'));
                  }
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

    });
  </script>
            
@endsection