routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()) {
        return redirect()->route('home');
    }
    return view('auth.login');
});

Auth::routes();

Route::get('test', function() {
    Storage::disk('google')->put('test.txt', 'Hello World');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');

	//Master
    Route::group(['namespace' => 'Masters', 'prefix' => 'master'], function() {
       // Route::get('master/location-centre-master', 'LocationCentreMaster');
        
        Route::resource('location-centre-master', 'LocationCentreMasterController');
        
        Route::resource('department-centre-master', 'DepartmentCentreMasterController');
      	
      	Route::get('get-employee-details/{id}', 'EmployeeMasterController@get_employee_details')->name('getEmployeeDetails');
        Route::resource('employee-master', 'EmployeeMasterController');

        Route::resource('project-master', 'ProjectMasterController');

        Route::resource('beneficiary-master', 'BeneficiaryMasterController');

        Route::resource('holiday-master', 'HolidayMasterController');

        Route::resource('office-hours-master', 'OfficeHoursMasterController');

        Route::resource('roles','RoleMasterController');


    });

    //Attendance
    Route::group(['namespace' => 'Attendance', 'prefix' => 'attendance'], function() {
        
        Route::get('location-details', 'MarkAttendanceController@ip_details')->name('getLocation');
        Route::get('show-attendance', 'MarkAttendanceController@show_attendance_index')->name('showAttendance');
        Route::post('show-attendance', 'MarkAttendanceController@find_attendance')->name('findAttendance');
        Route::resource('mark-attendance', 'MarkAttendanceController');

    });

    //Outdoor Duty
    Route::group(['namespace' => 'OutdoorDuty'], function() {
        
        Route::put('outdoor-duty/email-list/delete/{id?}', 'EmailListController@delete')->name('delete_email');
        Route::resource('outdoor-duty/email-list', 'EmailListController', ['names' => 'email-list']);

        Route::put('outdoor-duty/approval-process/{id}', 'OutdoorDutyController@approval_process');
        Route::resource('outdoor-duty', 'OutdoorDutyController');

    });

    //leave-application
    Route::group(['namespace' => 'LeaveApplication'], function() {
        
        Route::put('leave-application/approval-process/{id}', 'LeaveApplicationController@approval_process');
        Route::resource('leave-application', 'LeaveApplicationController');

    });

    //Report
    Route::group(['namespace' => 'Report', 'prefix' => 'reports'], function() {
        
        Route::get('export-attendance', 'AttendanceReportController@export_attendance')->name('export-attendance');
        Route::get('export-attendance-horizontal', 'AttendanceReportController@export_attendance_horizontal')->name('export-attendance-horizontal');
        Route::get('attendance-report', 'AttendanceReportController@index')->name('attendance-report.index');

    });

        //Content Manager
        Route::group(['namespace' => 'ContentManager', 'prefix' => 'content-manager'], function() {
           // Route::get('master/location-centre-master', 'LocationCentreMaster');
            
            Route::get('get-access-token', 'UploadContentController@get_access_token');
            Route::resource('upload-content', 'UploadContentController');
            
            Route::resource('pending-approval-content', 'PendingApprovalContentController');

            Route::get('approved-content', 'ApprovedContentController@index')->name('approved-content.index');
        });
});

Route::get('get-google-drive-file', function() {
    $filename = 'banner_-_3_82.png';

    $dir = '/';
    $recursive = false; // Get subdirectories also?
    $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

    $file = $contents
        ->where('type', '=', 'file')
        ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME))
        ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION))
        ->first(); // there can be duplicate file names!

    dd($file['path']);

    $rawData = Storage::disk('google')->get($file['path']);

    return response($rawData, 200)
        ->header('ContentType', $file['mimetype'])
        ->header('Content-Disposition', "attachment; filename='$filename'");
});


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

});

Route::get('clock-in-reminder', 'Commands\AttendanceReminderController@clock_in_reminder');
Route::get('clock-out-reminder', 'Commands\AttendanceReminderController@clock_out_reminder');
Route::get('update-attendance-status', 'Commands\UpdateAttendanceStatusController@index');

app/Http/Controllers/Masters/BeneficiaryMasterController.php
<?php

namespace App\Http\Controllers\Masters;

use App\Model\Masters\BeneficiaryMaster;
use Illuminate\Http\Request;
use App\Model\Masters\ProjectMaster;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Illuminate\Support\Collection;
class BeneficiaryMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $beneficiaries = [];
        // return $request->all();
         if (count((array)$request->all()) == 0) {
            \Session::forget('data');
            $beneficiaries = BeneficiaryMaster::orderBy('id', 'asc');
        }
        else {
            if(isset($request->search) && count($request->search) > 0)
            {
                \Session::forget('data');
            }
            \Session::push('data', $request->search);
             $beneficiaries = BeneficiaryMaster::orderBy('id', 'asc');
            if (count((array)\Session::get('data')[0]) > 0) {
                                
                $query = BeneficiaryMaster::orderBy('id', 'asc');
                
                foreach (\Session::get('data')[0] as $beneficiary)
                {
                    
                    if( $beneficiary['column'] == 'name' ){
                        $query->where('name', 'LIKE', '%'. $beneficiary['search_data'] .'%');
                    }
                    if( $beneficiary['column'] == 'mobile_number' ){
                        $query->where('mobile_number', $beneficiary['search_data']);
                    }
                    if( $beneficiary['column'] == 'address' ){
                        $query->where('name', 'LIKE', '%'. $beneficiary['search_data'] .'%');
                    }
                    if( $beneficiary['column'] == 'photo_name' ){
                        $query->where('name', 'LIKE', '%'. $beneficiary['search_data'] .'%');
                    }
                    if( $beneficiary['column'] == 'project' ){
                        $query->WhereHas('project', function ($query1) use ($beneficiary) {
                            $query1->where('name', 'LIKE', '%' . $beneficiary['search_data'] . '%');
                        });
                    }

                    if( $beneficiary['column'] == 'status' ){
                        if( $beneficiary['search_data'] == "active" )
                            $query->where('active', 1);
                        elseif( $beneficiary['search_data'] == "inactive" )
                            $query->where('active', 0);
                    }

                    
                }
                $beneficiaries = $query;
                
            }
        }

        $beneficiaries = $beneficiaries->paginate(10);
        $columns = ['name','project','mobile_number','address','photo_name' ,'status',];
        return view('masters.beneficiary_master.index',compact('columns','beneficiaries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $project = ProjectMaster::find($request->project_id);

        if( !isset($request->project_id)){

            session()->flash('status',"Project Not Available");
            return redirect()->route('project-master.index');
        }
        if( $project == NULL ){

            session()->flash('status',"Project Not Found");
            return redirect()->route('project-master.index');
        }


        return view('masters.beneficiary_master.create', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = $request->except('_token');
        $data['photo_name'] = $request->photo->getClientOriginalName();

        \DB::beginTransaction();
        $beneficiary = BeneficiaryMaster::create($data);


        if(isset($request->photo))
        {
            $file = $request->photo;
            $file_name = explode(".", $file->getClientOriginalName());
            $filename = $file_name[0];
            $ext = $file_name[ sizeof($file_name)-1 ];
            $data['file_path'] = '/uploads/beneficiaries';
            $data['beneficiary_file_name'] = str_replace(' ', '_', strtolower($request->name))."_".$beneficiary->id. '.' . $ext;

            $destinationPath = 'uploads/beneficiaries';

            if ($file->move($destinationPath, $data['beneficiary_file_name'])) {
                
            }
        }
        \DB::commit();

        session()->flash('status',"Beneficiary Added");
        return redirect()->route('beneficiary-master.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function show(BeneficiaryMaster $beneficiaryMaster)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $beneficiary = BeneficiaryMaster::find($id);
        return view('masters.beneficiary_master.edit', compact('beneficiary'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_token');
        $data['photo_name'] = $request->photo->getClientOriginalName();

        \DB::beginTransaction();
        $beneficiary = BeneficiaryMaster::find($id);
        $update = $beneficiary->update($data);

        if(isset($request->photo))
        {
            $file = $request->photo;
            $file_name = explode(".", $file->getClientOriginalName());
            $filename = $file_name[0];
            $ext = $file_name[ sizeof($file_name)-1 ];
            $data['file_path'] = '/uploads/beneficiaries';
            $data['beneficiary_file_name'] = str_replace(' ', '_', strtolower($beneficiary->name))."_".$id. '.' . $ext;

            $destinationPath = 'uploads/beneficiaries';

            if ($file->move($destinationPath, $data['beneficiary_file_name'])) {
                
            }
        }
        \DB::commit();

        session()->flash('status',"Beneficiary Updated Successfully");
        return redirect()->route('beneficiary-master.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function destroy(BeneficiaryMaster $beneficiaryMaster)
    {
        //
    }
}

app/Http/Controllers/Masters/OfficeHoursMasterController.php
<?php

namespace App\Http\Controllers\Masters;

use App\Model\Masters\OfficeHoursMaster;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Illuminate\Support\Collection;
class OfficeHoursMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $office_hours = OfficeHoursMaster::get();
        $count = OfficeHoursMaster::count(); // to check if a row already exists or not in the table. Only one row is allowed.
        return view('masters.office_hours_master.index', compact('office_hours', 'count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('masters.office_hours_master.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([ 
            'start_of_day' => 'required', 
            'end_of_day' => 'required', 
            'late_cutoff_time' => 'required', 
            'half_day_cutoff_time' => 'required', 
        ]);

        $data = $request->all();
        $data['created_by'] = \Auth::user()->id;
        OfficeHoursMaster::create($data);

        session()->flash('status',"Office Hours Successfully Created");
        return redirect()->route('office-hours-master.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function show(OfficeHoursMaster $officeHoursMaster)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $office_hours = OfficeHoursMaster::find($id);
        return view('masters.office_hours_master.edit', compact('office_hours'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([ 
            'start_of_day' => 'required', 
            'end_of_day' => 'required', 
            'late_cutoff_time' => 'required', 
            'half_day_cutoff_time' => 'required', 
        ]);

        $data = $request->all();
        $data['updated_by'] = \Auth::user()->id;
        OfficeHoursMaster::find($id)->update($data);

        session()->flash('status',"Office Hours Successfully Updated");
        return redirect()->route('office-hours-master.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function destroy(OfficeHoursMaster $officeHoursMaster)
    {
        //
    }
}

resources/views/masters/employee_master/index.blade.php
@extends('layouts.app', ['activePage' => 'employee-master', 'titlePage' => __('Employee Master')])

@section('title')Employee Master @endsection

@section('page-level-css')
    <link href="{{ asset('material') }}/plugins/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary" data-color="orange">
        <h4 class="card-title">Employee Master </h4>
      </div>
      <div class="card-body">
        <div id="location_centre_Master">
          <div class="table-toolbar">
                      <div class="row">
                        <div class="col-md-12">
                          <label for="" class="caption font-green">Search Employees</label>
                          <lable class="pull-right">
                            <a class="btn fa fa-plus add-fields" href="{{ route('employee-master.create') }}"> Create Employee</a>
                          </lable>
                          
                        </div>
                      </div>
                        <hr>

                        <form method="get" action="{{route('employee-master.index')}}">
                          <div class="row">
                            @if( count((array)\Session::get('data')[0] ) > 0 )
                              @foreach( \Session::get('data')[0] as $input_key => $input)
                                <div class="col-md-12 search_fields">
                                  <div class="row">
                                    <div class=" col-md-4">
                                        <label>Column Name</label>
                                        <select name="search[{{$input_key}}][column]" class="column form-control selectpicker" data-live-search="true" id="column_names">
                                            <option value="">Select Search</option>
                                            @foreach($columns as $key => $column)
                                                <option value="{{$column}}"
                                                @if( $input[ "column" ] == $column )
                                                    selected="selected"
                                                @endif
                                                >{{ucwords(str_replace("_", " ", $column))}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class=" col-md-4">
                                        <label>Search Data</label>
                                        @if(isset($input['search_data']))
                                            @if($input[ "column" ] == "status" && is_array($input['search_data']))
                                                <input type="text" name="search[{{$input_key}}][search_data]" class="form-control search_data" value="{{implode(',',$input['search_data']) }}" placeholder="Enter data">
                                            @else
                                                <input type="text" name="search[{{$input_key}}][search_data]" class="form-control search_data" value="{{ $input['search_data'] }}" placeholder="Enter data">
                                            @endif
                                        @else
                                            <input type="text" name="search[{{$input_key}}][search_data]" class="form-control search_data" placeholder="Enter data" required>
                                        @endif
                                    </div>
                                    @if( $input_key != 0 )
                                        <div class="form-group col-md-4">
                                            <i class="fa fa-trash fa-lg btn  remove-fields "></i>
                                        </div>
                                    @else
                                        <div class="form-group col-md-4">
                                            <i class="fa fa-plus fa-lg btn hide add-fields "></i>
                                        </div>
                                    @endif
                                    
                                  </div>
                                </div>
                              @endforeach
                              <div class="additional_fields">
                                
                              </div>
                            @else
                              <div class="col-md-12 search_fields">
                                <div class="row">
                                  <div class=" col-md-4">
                                      <label>Column Name</label>
                                      <select name="search[0][column]" class="column form-control selectpicker" data-live-search="true" id="column_names">
                                          <option value="">Select Search</option>
                                          @foreach($columns as $key => $column)
                                              <option value="{{$column}}">{{ucwords(str_replace("_", " ", $column))}}</option>
                                          @endforeach
                                      </select>
                                  </div>
                                  <div class=" col-md-4">
                                      <label>Search Data</label>
                                      <input type="text" name="search[0][search_data]" class=" form-control search_data" placeholder="Enter data">
                                  </div>
                                  <div class=" col-md-4">
                                    <div class="icon_container">
                                      <i class="fa fa-plus fa-lg btn add-fields"></i>
                                    </div>
                                  </div>
                                  
                                </div>
                              </div>
                              <div class="additional_fields">
                                
                              </div>
                            @endif

                              <div class="col-md-12">
                                <div class="row">
                                  <div class=" col-md-2">
                                      <button type="submit" class=" btn green find_parent">Find</button>
                                  </div>
                                </div>
                              </div>
                          </div>
                        </form>

                    </div>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-body" style="overflow: auto;">
        <div class="">
          
          <table class="table  table-striped table-bordered table-hove">
            <tr>
              <th>Action</th>
              <th>Employee Name</th>
              <th>Mobile Number</th>
              <th>Employee UID</th>
              <th>Email ID</th>
              <th> Manager</th>
              <th> Location Centre</th>
              <th> Department Centre</th>
              <th> Role </th>
              <th> Bypass Late Remarks </th>
              <th>Status</th>
            </tr>

            @foreach($employees as $employee)
              <tr>
                <td> 
                  <a href="{{ url('master/employee-master/'.$employee->id.'/edit') }}" class="fa fa-pencil"></a> 
                </td>
                <td>{{ $employee->name }}</td>
                <td>{{ $employee->mobile_number }}</td>
                <td>{{ $employee->employee_uid }}</td>
                <td>{{ $employee->email_id }}</td>
                <td>
                  @if( !is_null($employee->manager) )
                    {{ $employee->manager->name }}
                  @endif
                </td>
                <td>
                  @if( !is_null($employee->location_centre) )
                    {{ $employee->location_centre->name }}
                  @endif
                </td>
                <td>
                  @if( !is_null($employee->department_centre) )
                    {{ $employee->department_centre->name }}
                  @endif
                </td>
                <td>
                  @if( !is_null($employee->roles->first()) )
                    {{$employee->roles->first()->name}}
                  @endif
                </td>
                <td>
                  @if( $employee->bypass_late_remarks == 0 )
                    No
                  @else
                    Yes
                  @endif
                </td>
                <td>
                  @if( $employee->active == 1 )
                    Active
                  @else
                    Inactive
                  @endif
                </td>
              </tr>
            @endforeach
          </table>
          {{$employees->render()}}
        </div>

      </div>
    </div>

  </div>
</div>
@endsection

@section('page-level-plugins-js')
    <script src="{{ URL::asset('template/assets/global/plugins/scripts/datatable.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-select/js/bootstrap-select.min.js') }}"
            type="text/javascript"></script>
@endsection

@section('page-level-scripts-js')
  @if(Session::has('status'))
      <script>alert('{{Session::get('status')}}');</script>
  @endif

  <script type="text/javascript">
    
    $(document).ready(function(){

      $('.add-fields').click(function(){
        search_fields = $(this).parents('.search_fields');  
        new_row = $(search_fields).clone().eq(0);
        var time = new Date().getTime();

        $(new_row).find('.column').attr('name','search['+time+'][column]');
        $(new_row).find('.column').attr('id','search['+time+'][column]');
        $(new_row).find('.search_data').attr('name','search['+time+'][search_data]');
        $(new_row).find('.fa-plus').removeClass('fa-plus').addClass('fa-trash remove-fields');

        $(new_row).find('select').each(function(){
            var name = $(this).data('name');
            $(this).val('');
            $(this).siblings('div').remove();
            $(this).siblings('button').remove();
        });
        $(new_row).find('.selectpicker').selectpicker('refresh');
        new_row.find('.search_data').val('');

        $('.additional_fields').append(new_row);
        
      })

      $(document).on('click','.remove-fields', function(){
        $(this).parents('.search_fields').remove();
      });

    })

  </script>
@endsection