routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(Auth::check()) {
        return redirect()->route('home');
    }
    return view('auth.login');
});

Auth::routes();

Route::get('test', function() {
    Storage::disk('google')->put('test.txt', 'Hello World');
});

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');

	//Master
    Route::group(['namespace' => 'Masters', 'prefix' => 'master'], function() {
       // Route::get('master/location-centre-master', 'LocationCentreMaster');
        
        Route::resource('location-centre-master', 'LocationCentreMasterController');
        
        Route::resource('department-centre-master', 'DepartmentCentreMasterController');
      	
      	Route::get('get-employee-details/{id}', 'EmployeeMasterController@get_employee_details')->name('getEmployeeDetails');
        Route::resource('employee-master', 'EmployeeMasterController');

        Route::resource('project-master', 'ProjectMasterController');

        Route::resource('beneficiary-master', 'BeneficiaryMasterController');

        Route::resource('holiday-master', 'HolidayMasterController');

        Route::resource('office-hours-master', 'OfficeHoursMasterController');

        Route::resource('roles','RoleMasterController');


    });

    //Attendance
    Route::group(['namespace' => 'Attendance', 'prefix' => 'attendance'], function() {
        
        Route::get('location-details', 'MarkAttendanceController@ip_details')->name('getLocation');
        Route::get('show-attendance', 'MarkAttendanceController@show_attendance_index')->name('showAttendance');
        Route::post('show-attendance', 'MarkAttendanceController@find_attendance')->name('findAttendance');
        Route::resource('mark-attendance', 'MarkAttendanceController');

    });

    //Outdoor Duty
    Route::group(['namespace' => 'OutdoorDuty'], function() {
        
        Route::put('outdoor-duty/email-list/delete/{id?}', 'EmailListController@delete')->name('delete_email');
        Route::resource('outdoor-duty/email-list', 'EmailListController', ['names' => 'email-list']);

        Route::put('outdoor-duty/approval-process/{id}', 'OutdoorDutyController@approval_process');
        Route::resource('outdoor-duty', 'OutdoorDutyController');

    });

    //leave-application
    Route::group(['namespace' => 'LeaveApplication'], function() {
        
        Route::put('leave-application/approval-process/{id}', 'LeaveApplicationController@approval_process');
        Route::resource('leave-application', 'LeaveApplicationController');

    });

    //Report
    Route::group(['namespace' => 'Report', 'prefix' => 'reports'], function() {
        
        Route::get('export-attendance', 'AttendanceReportController@export_attendance')->name('export-attendance');
        Route::get('export-attendance-horizontal', 'AttendanceReportController@export_attendance_horizontal')->name('export-attendance-horizontal');
        Route::get('attendance-report', 'AttendanceReportController@index')->name('attendance-report.index');

    });

        //Content Manager
        Route::group(['namespace' => 'ContentManager', 'prefix' => 'content-manager'], function() {
           // Route::get('master/location-centre-master', 'LocationCentreMaster');
            
            Route::get('get-access-token', 'UploadContentController@get_access_token');
            Route::resource('upload-content', 'UploadContentController');
            
            Route::resource('pending-approval-content', 'PendingApprovalContentController');

            Route::get('approved-content', 'ApprovedContentController@index')->name('approved-content.index');
        });
});

Route::get('get-google-drive-file', function() {
    $filename = 'banner_-_3_82.png';

    $dir = '/';
    $recursive = false; // Get subdirectories also?
    $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

    $file = $contents
        ->where('type', '=', 'file')
        ->where('filename', '=', pathinfo($filename, PATHINFO_FILENAME))
        ->where('extension', '=', pathinfo($filename, PATHINFO_EXTENSION))
        ->first(); // there can be duplicate file names!

    dd($file['path']);

    $rawData = Storage::disk('google')->get($file['path']);

    return response($rawData, 200)
        ->header('ContentType', $file['mimetype'])
        ->header('Content-Disposition', "attachment; filename='$filename'");
});


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

});

Route::get('clock-in-reminder', 'Commands\AttendanceReminderController@clock_in_reminder');
Route::get('clock-out-reminder', 'Commands\AttendanceReminderController@clock_out_reminder');
Route::get('update-attendance-status', 'Commands\UpdateAttendanceStatusController@index');

app/Http/Controllers/Masters/BeneficiaryMasterController.php
<?php

namespace App\Http\Controllers\Masters;

use App\Model\Masters\BeneficiaryMaster;
use Illuminate\Http\Request;
use App\Model\Masters\ProjectMaster;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Illuminate\Support\Collection;
class BeneficiaryMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $beneficiaries = [];
        // return $request->all();
         if (count((array)$request->all()) == 0) {
            \Session::forget('data');
            $beneficiaries = BeneficiaryMaster::orderBy('id', 'asc');
        }
        else {
            if(isset($request->search) && count($request->search) > 0)
            {
                \Session::forget('data');
            }
            \Session::push('data', $request->search);
             $beneficiaries = BeneficiaryMaster::orderBy('id', 'asc');
            if (count((array)\Session::get('data')[0]) > 0) {
                                
                $query = BeneficiaryMaster::orderBy('id', 'asc');
                
                foreach (\Session::get('data')[0] as $beneficiary)
                {
                    
                    if( $beneficiary['column'] == 'name' ){
                        $query->where('name', 'LIKE', '%'. $beneficiary['search_data'] .'%');
                    }
                    if( $beneficiary['column'] == 'mobile_number' ){
                        $query->where('mobile_number', $beneficiary['search_data']);
                    }
                    if( $beneficiary['column'] == 'address' ){
                        $query->where('name', 'LIKE', '%'. $beneficiary['search_data'] .'%');
                    }
                    if( $beneficiary['column'] == 'photo_name' ){
                        $query->where('name', 'LIKE', '%'. $beneficiary['search_data'] .'%');
                    }
                    if( $beneficiary['column'] == 'project' ){
                        $query->WhereHas('project', function ($query1) use ($beneficiary) {
                            $query1->where('name', 'LIKE', '%' . $beneficiary['search_data'] . '%');
                        });
                    }

                    if( $beneficiary['column'] == 'status' ){
                        if( $beneficiary['search_data'] == "active" )
                            $query->where('active', 1);
                        elseif( $beneficiary['search_data'] == "inactive" )
                            $query->where('active', 0);
                    }

                    
                }
                $beneficiaries = $query;
                
            }
        }

        $beneficiaries = $beneficiaries->paginate(10);
        $columns = ['name','project','mobile_number','address','photo_name' ,'status',];
        return view('masters.beneficiary_master.index',compact('columns','beneficiaries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $project = ProjectMaster::find($request->project_id);

        if( !isset($request->project_id)){

            session()->flash('status',"Project Not Available");
            return redirect()->route('project-master.index');
        }
        if( $project == NULL ){

            session()->flash('status',"Project Not Found");
            return redirect()->route('project-master.index');
        }


        return view('masters.beneficiary_master.create', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = $request->except('_token');
        $data['photo_name'] = $request->photo->getClientOriginalName();

        \DB::beginTransaction();
        $beneficiary = BeneficiaryMaster::create($data);


        if(isset($request->photo))
        {
            $file = $request->photo;
            $file_name = explode(".", $file->getClientOriginalName());
            $filename = $file_name[0];
            $ext = $file_name[ sizeof($file_name)-1 ];
            $data['file_path'] = '/uploads/beneficiaries';
            $data['beneficiary_file_name'] = str_replace(' ', '_', strtolower($request->name))."_".$beneficiary->id. '.' . $ext;

            $destinationPath = 'uploads/beneficiaries';

            if ($file->move($destinationPath, $data['beneficiary_file_name'])) {
                
            }
        }
        \DB::commit();

        session()->flash('status',"Beneficiary Added");
        return redirect()->route('beneficiary-master.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function show(BeneficiaryMaster $beneficiaryMaster)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $beneficiary = BeneficiaryMaster::find($id);
        return view('masters.beneficiary_master.edit', compact('beneficiary'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->except('_token');
        $data['photo_name'] = $request->photo->getClientOriginalName();

        \DB::beginTransaction();
        $beneficiary = BeneficiaryMaster::find($id);
        $update = $beneficiary->update($data);

        if(isset($request->photo))
        {
            $file = $request->photo;
            $file_name = explode(".", $file->getClientOriginalName());
            $filename = $file_name[0];
            $ext = $file_name[ sizeof($file_name)-1 ];
            $data['file_path'] = '/uploads/beneficiaries';
            $data['beneficiary_file_name'] = str_replace(' ', '_', strtolower($beneficiary->name))."_".$id. '.' . $ext;

            $destinationPath = 'uploads/beneficiaries';

            if ($file->move($destinationPath, $data['beneficiary_file_name'])) {
                
            }
        }
        \DB::commit();

        session()->flash('status',"Beneficiary Updated Successfully");
        return redirect()->route('beneficiary-master.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Masters\BeneficiaryMaster  $beneficiaryMaster
     * @return \Illuminate\Http\Response
     */
    public function destroy(BeneficiaryMaster $beneficiaryMaster)
    {
        //
    }
}

app/Http/Controllers/Masters/OfficeHoursMasterController.php
<?php

namespace App\Http\Controllers\Masters;

use App\Model\Masters\OfficeHoursMaster;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use Illuminate\Support\Collection;
class OfficeHoursMasterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $office_hours = OfficeHoursMaster::get();
        $count = OfficeHoursMaster::count(); // to check if a row already exists or not in the table. Only one row is allowed.
        return view('masters.office_hours_master.index', compact('office_hours', 'count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('masters.office_hours_master.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([ 
            'start_of_day' => 'required', 
            'end_of_day' => 'required', 
            'late_cutoff_time' => 'required', 
            'half_day_cutoff_time' => 'required', 
        ]);

        $data = $request->all();
        $data['created_by'] = \Auth::user()->id;
        OfficeHoursMaster::create($data);

        session()->flash('status',"Office Hours Successfully Created");
        return redirect()->route('office-hours-master.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function show(OfficeHoursMaster $officeHoursMaster)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $office_hours = OfficeHoursMaster::find($id);
        return view('masters.office_hours_master.edit', compact('office_hours'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([ 
            'start_of_day' => 'required', 
            'end_of_day' => 'required', 
            'late_cutoff_time' => 'required', 
            'half_day_cutoff_time' => 'required', 
        ]);

        $data = $request->all();
        $data['updated_by'] = \Auth::user()->id;
        OfficeHoursMaster::find($id)->update($data);

        session()->flash('status',"Office Hours Successfully Updated");
        return redirect()->route('office-hours-master.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Masters\OfficeHoursMaster  $officeHoursMaster
     * @return \Illuminate\Http\Response
     */
    public function destroy(OfficeHoursMaster $officeHoursMaster)
    {
        //
    }
}

resources/views/masters/beneficiary_master/create.blade.php
@extends('layouts.app', ['activePage' => 'beneficiary-master', 'titlePage' => __('Beneficiary Master')])

@section('title') Create Beneficiary @endsection


@section('page-level-css')
    <link href="{{ asset('material') }}/plugins/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css')}}" rel="stylesheet" type="text/css" />
    <style type="text/css">
      td{
        padding: 10px;
      }

      input.form-control.upload-file {
          padding: 2px;
      }
    </style>
@endsection

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary" data-color="orange">
        <h4 class="card-title">Create Beneficiary </h4>
      </div>
      <div class="card-body">
        @if(count($errors) > 0)
            <div class="alert alert-danger">
                <h6> Errors </h6>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="POST" action="{{ route('beneficiary-master.store') }}" enctype="multipart/form-data">
          @csrf
          <div class="row">
            <div class="col-md-12">
              <label>Project Name :</label>
              <h5> {{ $project->name }} </h5>
              <input type="hidden" name="project_id" value="{{ $project->id }}">

            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-4">
              <label>Beneficiary Name</label>
              <input type="text" name="name" class="form-control" value="{{ old('name', '') }}" placeholder="Enter Name of Beneficiary">
            </div>


            <div class="col-md-4">
              <label>Mobile Number</label>
              <input type="number" maxlength="10" minlength="10" name="mobile_number" class="form-control" value="{{ old('mobile_number', '') }}" placeholder="Enter Mobile Number">
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <label> Address </label>
              <textarea class="form-control" name="address" placeholder="Enter Beneficiary Address">{{ old('address', '') }}</textarea>
            </div>

            <div class="col-md-4" style="padding: 15px;">
              <label>Status</label>
              <table>
                <tr>
                  <td>
                      <input type="radio" name="active" class="" value="1" 
                      @if( old('active', 1) == "1" )
                        checked="checked"
                      @endif
                      > Active
                  </td>
                  <td>
                      <input type="radio" name="active" class="" value="0"
                      @if( old('active', '') == "0" )
                        checked="checked"
                      @endif
                      > Inactive
                  </td>
                </tr>
              </table>
            </div>

            
          </div>

          <div class="row">
            <div class="col-md-6">
                <label>Photo </label>
                <input type="File" class="form-control upload-file" name="photo" placeholder="Enter Reward Link for campaign" accept=" .jpeg, .png, .jpg">
            </div>

            <div class="col-md-6">
                <div class="type2 ">
                    
                    <label style="display: block;"> File Preview: </label>

                        <iframe class="file_preview" src="" width="500" height="300"></iframe>
                        <img class="img_preview" src="" width="500" height="300">
                </div>
            </div>
          </div>

        </div>


          <div class="row">
            <div class="col-md-3 offset-4">
              <input type="submit" name="" class="btn" value="Submit" style="width: 100%; background-color: #fa9f19; font-weight: 600; color: #fff;">
            </div>
          </div>
          
        </form>

      </div>
    </div>

  </div>
</div>
@endsection

@section('page-level-plugins-js')
    <script src="{{ URL::asset('template/assets/global/plugins/scripts/datatable.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-select/js/bootstrap-select.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>

@endsection

@section('page-level-scripts-js')
  <script src="{{ URL::asset('template/assets/pages/scripts/components-date-time-pickers.js')}}" type="text/javascript"></script>

  <script type="text/javascript">
    

    $(document).ready(function(){

      $('.img_preview').hide();

        $("#financial_year").datepicker({
            format      :   "yy",
            viewMode    :   "years", 
        });
        
        $('body').delegate('.upload-file', 'change', function () {
            readURL(this);
        })
        
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {

                    var file = input.files[0];
                    var fileType = file["type"];
                        console.log( file);
                    var validImageTypes = ["application/"];
                    if( fileType == "image/jpeg" || fileType == "image/jpg" || fileType == "image/png"){
                        $('.file_preview').hide();
                        $('.img_preview').show();
                        $('.img_preview').attr('src', e.target.result);
                        $('.img_preview').show();
                    }
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    });
  </script>
            
@endsection

resources/views/masters/beneficiary_master/edit.blade.php
@extends('layouts.app', ['activePage' => 'beneficiary-master', 'titlePage' => __('Beneficiary Master')])

@section('title') Create Beneficiary @endsection


@section('page-level-css')
    <link href="{{ asset('material') }}/plugins/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css')}}" rel="stylesheet" type="text/css" />
    <style type="text/css">
      td{
        padding: 10px;
      }

      input.form-control.upload-file {
          padding: 2px;
      }
    </style>
@endsection

@section('content')
<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary" data-color="orange">
        <h4 class="card-title">Edit Beneficiary </h4>
      </div>
      <div class="card-body">
        @if(count($errors) > 0)
            <div class="alert alert-danger">
                <h6> Errors </h6>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="POST" action="{{ route('beneficiary-master.update', $beneficiary->id) }}" enctype="multipart/form-data">
          @csrf
          @method('PATCH')

          <div class="row">
            <div class="col-md-12">
              <label>Project Name :</label>
              <h5> {{ $beneficiary->project->name }} </h5>
              <input type="hidden" name="project_id" value="{{ $beneficiary->project_id }}">

            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-4">
              <label>Beneficiary Name</label>
              <input type="text" name="name" class="form-control" value="{{ old('name', $beneficiary->name) }}" placeholder="Enter Name of Beneficiary">
            </div>


            <div class="col-md-4">
              <label>Mobile Number</label>
              <input type="number" maxlength="10" minlength="10" name="mobile_number" class="form-control" value="{{ old('mobile_number', $beneficiary->mobile_number) }}" placeholder="Enter Mobile Number">
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <label> Address </label>
              <textarea class="form-control" name="address" placeholder="Enter Beneficiary Address">{{ old('address', $beneficiary->address) }}</textarea>
            </div>

            <div class="col-md-4" style="padding: 15px;">
              <label>Status</label>
              <table>
                <tr>
                  <td>
                      <input type="radio" name="active" class="" value="1" 
                      @if( old('active', $beneficiary->active) == "1" )
                        checked="checked"
                      @endif
                      > Active
                  </td>
                  <td>
                      <input type="radio" name="active" class="" value="0"
                      @if( old('active', $beneficiary->active) == "0" )
                        checked="checked"
                      @endif
                      > Inactive
                  </td>
                </tr>
              </table>
            </div>

            
          </div>

          <div class="row">
            <div class="col-md-6">
              @php
                $file_name = explode('.',$beneficiary->photo_name);
                $ext = $file_name[ sizeof($file_name)-1 ];

                $file = "\uploads\beneficiaries\\".str_replace(" ", "_", strtolower($beneficiary->name))."_".$beneficiary->id.".".$ext;
              @endphp


              <label>Photo </label>
              <input type="File" class="form-control upload-file" name="photo" placeholder="Enter Reward Link for campaign" accept=" .jpeg, .png, .jpg">
            </div>

            <div class="col-md-6">
                <div class="type2 ">
                    
                    <label style="display: block;"> File Preview: </label>

                        <iframe class="file_preview" src="" width="500" height="300"></iframe>
                        <img class="img_preview" src="{{ URL($file) }}" width="500" height="300">
                </div>
            </div>
          </div>

        </div>


          <div class="row">
            <div class="col-md-3 offset-4">
              <input type="submit" name="" class="btn" value="Submit" style="width: 100%; background-color: #fa9f19; font-weight: 600; color: #fff;">
            </div>
          </div>
          
        </form>

      </div>
    </div>

  </div>
</div>
@endsection

@section('page-level-plugins-js')
    <script src="{{ URL::asset('template/assets/global/plugins/scripts/datatable.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-select/js/bootstrap-select.min.js') }}"
            type="text/javascript"></script>
    <script src="{{ URL::asset('template/assets/global/plugins/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>

@endsection

@section('page-level-scripts-js')
  <script src="{{ URL::asset('template/assets/pages/scripts/components-date-time-pickers.js')}}" type="text/javascript"></script>

  <script type="text/javascript">
    

    $(document).ready(function(){

      $('.img_preview').show();
      $('.file_preview').hide();

        $("#financial_year").datepicker({
            format      :   "yy",
            viewMode    :   "years", 
        });
        
        $('body').delegate('.upload-file', 'change', function () {
            readURL(this);
        })
        
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {

                    var file = input.files[0];
                    var fileType = file["type"];
                        console.log( file);
                    var validImageTypes = ["application/"];
                    if( fileType == "image/jpeg" || fileType == "image/jpg" || fileType == "image/png"){
                        $('.file_preview').hide();
                        $('.img_preview').show();
                        $('.img_preview').attr('src', e.target.result);
                        $('.img_preview').show();
                    }
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
    });
  </script>
            
@endsection